global using System.Runtime.CompilerServices;
global using Ardalis.SharedKernel;
global using Lost_And_Found.Core.ContributorAggregate;
global using Lost_And_Found.UseCases.Contributors.Create;
global using MediatR;
global using Microsoft.Extensions.Logging;
global using NSubstitute;
global using Shouldly;
global using Xunit;
